CREATE DATABASE CD_HENRY;

/*
Criei meu 1º DB,
e vou por fazer o SGBD usá-lo
*/
USE CD_HENRY;

CREATE TABLE STUDENTS(
  MATRICULA INT(5), /* não posso esquecer a vírgula */
  NOME VARCHAR(30),
  EMAIL VARCHAR(50)
  );
  
DROP TABLE STUDENTS;

DROP DATABASE CD_HENRY;

ALTER TABLE STUDENTS ADD(
  TELEFONE VARCHAR(9),
  CURSO VARCHAR(40)
 );
 
/* INÍCIO DO PROCESSO DE RENOMEAÇÃO DAS COLUNAS*/ 
ALTER TABLE STUDENTS DROP COLUMN CURSO;

ALTER TABLE STUDENTS MODIFY TELEFONE VARCHAR(11);

/* ALTER TABLE STUDENTS RENAME TO ******; ->> SERVE PRA RENOMEAR A TABELA */
/* ALTER TABLE STUDENTS RENAME COLUMN NOME TO NAME; ->> SERVE PRA RENOMEAR A COLUNA */
ALTER TABLE STUDENTS RENAME COLUMN NOME TO NAME;

ALTER TABLE STUDENTS RENAME COLUMN MATRICULA TO COD;

ALTER TABLE STUDENTS RENAME COLUMN TELEFONE TO PHONE;

ALTER TABLE STUDENTS ADD COLUMN COURSE VARCHAR(40);

ALTER TABLE STUDENTS RENAME TO ESTUDANTES;

INSERT INTO STUDENTS
(COD, NAME, EMAIL, PHONE, COURSE)
VALUES
(12345, 'Henry', 'henry@gmail.com', '11111111111', 'DFS'),
(67890, 'Gisele', 'gisele@gmail.com', '22222222222', 'DFS'),
(09876, 'Cinthia', 'cinthia@gmail.com', '33333333333', 'DFS');

TRUNCATE TABLE STUDENTS;
/*TRUNCATE TIRA OS DADOS INSERIDOS NA TABELA, MAS MANTÉM SUAS CONFIGURAÇÕES*/

UPDATE STUDENTS SET NAME = 'Henry Santos';

SELECT * FROM STUDENTS WHERE COD = 67890;

UPDATE STUDENTS SET NAME = 'Gisele Santana'
WHERE COD = 67890;

UPDATE STUDENTS SET
    EMAIL = 'gisele.santana@gmail.com',
    COURSE = 'DS'
WHERE
    COD = 67890;
    
UPDATE STUDENTS SET
    NAME = 'Henry Santos',
    EMAIL = 'henry.santos@gmail.com',
    COURSE = 'DS'
WHERE
    COD = 12345;

UPDATE STUDENTS SET
    NAME = 'Cinthia Gonçalves',
    EMAIL = 'cinthia.goncalves@gmail.com',
    COURSE = 'DS'
WHERE
    COD = 98765;

DELETE FROM STUDENTS WHERE COD = 12345;

SELECT * FROM STUDENTS;
/* o * (asterisco) é para trazer tudo referente a uma tabela */

SELECT COD, NAME, PHONE, COURSE FROM STUDENTS;

SELECT NAME FROM STUDENTS WHERE COURSE = 'DS';

SELECT * FROM STUDENTS ORDER BY NAME ASC;
SELECT * FROM STUDENTS ORDER BY NAME DESC;
/* o ASC é pra ordem crescente, e o DESC é pra decrescente*/

SELECT COUNT(*) FROM STUDENTS WHERE COURSE = 'DS';
/* o count é pra saber a quantidade (quantidade de quê? não sei, mas ele conta)*/

SELECT COUNT(*) AS QTDE FROM STUDENTS;
/* esse AS aí é pra mudar a nomeclatura do count na hora de mostrar a quantidade)*/

ALTER TABLE STUDENTS
      ADD AGE INT(3),
      ADD PRESENCE INT (3),
      ADD MONTHLY_FEE FLOAT(5),
      ADD GENDER VARCHAR(1);
      
SElECT * FROM STUDENTS;

UPDATE STUDENTS SET
    AGE = 23,
    PRESENCE = 75,
    MONTHLY_FEE = 450,
    GENDER = 'F'
WHERE 
   COD = 67890;

UPDATE STUDENTS SET
    AGE = 41,
    PRESENCE = 100,
    MONTHLY_FEE = 350,
    GENDER = 'F'
WHERE 
   COD = 98765;
   
SELECT NAME, MONTHLY_FEE FROM STUDENTS;

SELECT AVG(AGE) AS 'Média de idade' FROM STUDENTS;

/* AVG = AVERAGE*/

SELECT SUM(MONTHLY_FEE) AS 'Total a receber'
FROM STUDENTS;

SELECT * FROM STUDENTS WHERE PRESENCE >=76;

SELECT * FROM STUDENTS WHERE NAME LIKE '_i%';

SELECT * FROM STUDENTS WHERE NAME LIKE 'R%' OR COURSE = 'DS';

ALTER TABLE STUDENTS ADD STATE VARCHAR(2);       

UPDATE STUDENTS SET
 STATE = 'BA'
WHERE
 COD IN(67890, 98765);
 
SElECT * FROM STUDENTS;
 
SELECT * FROM STUDENTS WHERE STATE IN ('BA');

SELECT * FROM STUDENTS WHERE STATE IN ('BA') AND COURSE = 'DS';
